- name: rhpam-rhdm-workshop-apb playbook to deprovision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    openshift_user:
    openshift_password:
    openshift_token:
    user_count: 5

  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules

  tasks:
  - name: login as super user with token
    shell: "oc login --token={{ openshift_token }} --insecure-skip-tls-verify=true"
    ignore_errors: true
    when:
      - openshift_token is defined
      - openshift_token is not none
      - openshift_token|trim() != ""

  - name: login as super user with pwd
    shell: "oc login -u {{ openshift_user }} -p {{ openshift_password }} --insecure-skip-tls-verify=true"
    ignore_errors: true
    when: >
      openshift_token is not defined or
      openshift_token is none or
      openshift_token|trim() == ""

  - name: Delete infrastructure services from {{ namespace }}
    command: "oc delete all,cm,secret,pvc,sa -l app={{ item }} -n {{ namespace }}"
    ignore_errors: true
    with_items:
      - postgresql-ephemeral
      - rhpam73-authoring

  - name: Delete BC service account
    command: oc delete sa/businesscentral-service-account -n {{namespace}}
    ignore_errors: true

  - name: Delete KIE-Server service account
    command: oc delete sa/kieserver-service-account -n {{ namespace }}
    ignore_errors: true

  - name: Delete BC secrets
    command: oc delete secret/businesscentral-app-secret
    ignore_errors: true

  - name: Delete KIE-Server secrets
    command: oc delete secret/kieserver-app-secret
    ignore_errors: true


  #- name: Delete user projects.
  #  command: "oc delete project rhpam-user{{item}}"
  #  ignore_errors: true
  #  with_sequence: start=1 end={{user_count}}
