---

# TODO: Replace the ImageStream approach with Binary Builds from a Dockerfile that patch the BC and KIE-Server images with PMML support and Prometheus Metrics Provider.

- name: Debug message
  debug:
    msg: "Adding jPMML support to RHPAM 7.5."

- name: Create Business Central DMN PMML build
  shell: oc new-build --strategy docker --image-stream="openshift/rhpam75-businesscentral-openshift:1.0" --binary --name rhpam75-businesscentral-openshift-dmn-pmml -n {{ OCP_PROJECT }}

- name: Create KIE-Server DMN PMML build
  shell: oc new-build --strategy docker --image-stream="openshift/rhpam75-kieserver-openshift:1.0" --binary --name rhpam75-kieserver-openshift-dmn-pmml -n {{ OCP_PROJECT }}

- name: "Configure Business Central ImageStream"
  shell: "oc patch dc/rhpam7-rhpamcentr --type='json' -p '[{\"op\": \"replace\", \"path\": \"/spec/triggers/0/imageChangeParams/from/name\", \"value\": \"rhpam75-businesscentral-openshift-dmn-pmml:latest\"}]' -n {{ OCP_PROJECT }}"
  ignore_errors: true

- name: "Configure Business Central ImageStream Namespace"
  shell: "oc patch dc/rhpam7-rhpamcentr --type='json' -p '[{\"op\": \"replace\", \"path\": \"/spec/triggers/0/imageChangeParams/from/namespace\", \"value\": \"{{OCP_PROJECT}}\"}]' -n {{ OCP_PROJECT }}"
  ignore_errors: true

- name: "Configure KIE-Server ImageStream"
  shell: "oc patch dc/rhpam7-kieserver --type='json' -p '[{\"op\": \"replace\", \"path\": \"/spec/triggers/0/imageChangeParams/from/name\", \"value\": \"rhpam75-kieserver-openshift-dmn-pmml:latest\"}]' -n {{ OCP_PROJECT }}"
  ignore_errors: true

- name: "Configure KIE-Server ImageStream Namespace"
  shell: "oc patch dc/rhpam7-kieserver --type='json' -p '[{\"op\": \"replace\", \"path\": \"/spec/triggers/0/imageChangeParams/from/namespace\", \"value\": \"{{OCP_PROJECT}}\"}]' -n {{ OCP_PROJECT }}"
  ignore_errors: true

#------------------------------------ Disable the OpenShift Startup Strategy and revert to the old Controller Strategy  ------------------------------------------

- name: "Configure Business Central Environment Variables"
  shell: "oc set env dc/rhpam7-rhpamcentr KIE_WORKBENCH_CONTROLLER_OPENSHIFT_ENABLED=false"

- name: "Configure KIE-Server Environment Variables"
  shell: "oc set env dc/rhpam7-kieserver KIE_SERVER_STARTUP_STRATEGY=ControllerBasedStartupStrategy KIE_SERVER_CONTROLLER_USER=controllerUser KIE_SERVER_CONTROLLER_PWD=test1234! KIE_SERVER_CONTROLLER_SERVICE=rhpam7-rhpamcentr KIE_SERVER_CONTROLLER_PROTOCOL=ws"

#----------------------------------------------------------------------------------------------------------------------

- name: Start Business Central DMN PMML build
  shell: oc start-build rhpam75-businesscentral-openshift-dmn-pmml --from-dir {{ role_path }}/files/bc_docker_build -n {{ OCP_PROJECT }}

- name: Start KIE-Server DMN PMML Builds
  shell: oc start-build rhpam75-kieserver-openshift-dmn-pmml --from-dir {{ role_path }}/files/ks_docker_build -n {{ OCP_PROJECT }}
