kind: ImageStreamList
apiVersion: v1
metadata:
  name: rhpam73-bc-cm-image-streams
  annotations:
    description: ImageStream definitions for Red Hat Process Automation Manager 7.3 with Case Management Showcase
    openshift.io/provider-display-name: Red Hat, Inc.
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: rhpam73-businesscentral-openshift-cm-showcase
    annotations:
      openshift.io/display-name: Red Hat Process Automation Manager Business Central 7.3 with Case Management Showcase
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat Process Automation Manager 7.3 - Business Central with Case Management Showcase image.
        iconClass: icon-jboss
        tags: rhpam
        supports: rhpam:7.3
        version: '1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: quay.io/rhpam_rhdm/rhpam73-businesscentral-openshift-cm-showcase:1.0
