---

#---------------------- Deploy Grafana ----------------------

- name: Deploy Grafana
  shell: oc new-app grafana/grafana -n {{ OCP_PROJECT }}

# Expose Grafana via router
- name: Create route to Grafana
  shell: oc expose svc/grafana -n {{ OCP_PROJECT }}

#---------------------- Set facts ----------------------

- name: Get service account token
  shell: "oc sa get-token prom -n {{ OCP_PROJECT }}"
  register: oc_get_sa_token_output

- name: Set service account token fact
  set_fact:
    prom_sa_token: "{{ oc_get_sa_token_output.stdout }}"

- name: "Get Prometheus Route"
  shell: "oc get route prom -n {{ OCP_PROJECT }} | awk 'FNR > 1 {print $2}'"
  register: oc_get_route_prometheus_output

- name: "Set Prometheus Route fact"
  set_fact:
    prometheus_route: "{{ oc_get_route_prometheus_output.stdout }}"

- name: "Get Grafana Route"
  shell: "oc get route grafana -n {{ OCP_PROJECT }} | awk 'FNR > 1 {print $2}'"
  register: oc_get_route_grafana_output

- name: "Set Grafana Route fact"
  set_fact:
    grafana_route: "{{ oc_get_route_grafana_output.stdout }}"

#---------------------- Wait for Grafana deployment ----------------------

- include_tasks: ./wait_for_deploy.yml
  vars:
    pod_to_wait:
      - grafana

#---------------------- Configure Prometheus datasource ----------------------

- name: Create Grafana DataSource Request
  template:
    src: "{{ role_path }}/files/request-create-ds.js.orig"
    dest: "{{ role_path }}/files/request-create-ds.js"

- name: Create Prometheus DS
  uri:
    url: http://{{ grafana_route }}/api/datasources
    user: admin
    password: admin
    method: POST
    body: "{{ lookup('file','{{ role_path}}/files/request-create-ds.js') }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: False

#---------------------- Import Grafana dashboard ----------------------

- name: Create Grafana Dashboard
  uri:
    url: http://{{ grafana_route }}/api/dashboards/db
    user: admin
    password: admin
    method: POST
    body: "{{ lookup('file','{{ role_path}}/files/dashboard.json') }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: False
